# Copyright (C) The libssh2 project and its contributors.
#
# SPDX-License-Identifier: BSD-3-Clause

version = 1
SPDX-PackageName = "libssh2"
SPDX-PackageSupplier = "The libssh2 team <libssh2-devel@lists.haxx.se>"
SPDX-PackageDownloadLocation = "https://libssh2.org/"

# Test data
[[annotations]]
path = [
  "tests/ossfuzz/*",
  "tests/key_*",
  "tests/test_read_algos.txt",
  "ci/spellcheck-words.txt",
]
SPDX-FileCopyrightText = "The libssh2 project and its contributors."
SPDX-License-Identifier = "BSD-3-Clause"

# Test server
[[annotations]]
path = [
  "tests/openssh_server/.gitattributes",
  "tests/openssh_server/authorized_keys",
  "tests/openssh_server/ca_*",
  "tests/openssh_server/ssh_*",
  "tests/openssh_server/sshd_config",
]
SPDX-FileCopyrightText = "The libssh2 project and its contributors."
SPDX-License-Identifier = "BSD-3-Clause"

# Root files
[[annotations]]
path = [
  "NEWS",
  "README",
  "README.md",
  "RELEASE-NOTES",
]
SPDX-FileCopyrightText = "The libssh2 project and its contributors."
SPDX-License-Identifier = "BSD-3-Clause"

# Docs
[[annotations]]
path = [
  "docs/AUTHORS",
  "docs/BINDINGS.md",
  "docs/HACKING-CRYPTO",
  "docs/HACKING.md",
  "docs/INSTALL_CMAKE.md",
  "docs/Makefile.am",
  "docs/SECURITY.md",
  "docs/TODO",
  "docs/template.3",
  "os400/README400",
]
SPDX-FileCopyrightText = "The libssh2 project and its contributors."
SPDX-License-Identifier = "BSD-3-Clause"

# VMS
[[annotations]]
path = [
  "vms/libssh2_config.h",
  "vms/libssh2_make_example.dcl",
  "vms/libssh2_make_help.dcl",
  "vms/libssh2_make_kit.dcl",
  "vms/libssh2_make_lib.dcl",
  "vms/man2help.c",
  "vms/readme.vms",
]
SPDX-FileCopyrightText = "The libssh2 project and its contributors."
SPDX-License-Identifier = "BSD-3-Clause"

# Dotfiles
[[annotations]]
path = [
  ".checksrc",
  ".editorconfig",
  ".github/ISSUE_TEMPLATE/bug_report.md",
  ".github/SECURITY.md",
  ".gitignore",
  "docs/.gitignore",
  "example/.gitignore",
  "m4/.gitignore",
  "src/.gitignore",
  "tests/.gitignore",
]
SPDX-FileCopyrightText = "The libssh2 project and its contributors."
SPDX-License-Identifier = "BSD-3-Clause"
