name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_msvc:
    name: msvc
    runs-on: windows-latest
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - { arch: x64  , logging: OFF, shared: OFF, crypto: WinCNG, zlib: OFF }
          - { arch: x64  , logging: ON , shared: ON , crypto: WinCNG, zlib: OFF }
          - { arch: x64  , logging: OFF, shared: ON , crypto: WinCNG, zlib: OFF }
          - { arch: ARM64, logging: OFF, shared: ON , crypto: WinCNG, zlib: OFF }
          - { arch: x86  , logging: OFF, shared: ON , crypto: WinCNG, zlib: OFF }
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1
      - run: |
          vcpkg --triplet=${{ matrix.arch }}-windows install boringssl libgcrypt libressl openssl mbedtls wolfssl zlib
      - name: Configure with CMake
        shell: bash
        run: |
          platform=${{matrix.arch}}; [ "${platform}" = 'x86' ] && platform=Win32
          cmake . -B bin \
            -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_GENERATOR_PLATFORM=$platform \
            -DVCPKG_TARGET_TRIPLET=${{matrix.arch}}-windows \
            -DENABLE_WERROR=ON \
            -DBUILD_SHARED_LIBS=${{matrix.shared}} \
            -DCRYPTO_BACKEND=${{matrix.crypto}} \
            -DENABLE_ZLIB_COMPRESSION=${{matrix.zlib}}
      - name: Build with CMake
        shell: bash
        run: |
          cmake --build bin --config Release --target package
