name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_msvc:
    name: msvc
    runs-on: windows-latest
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - { arch: x64  , plat: windows, logging: OFF, shared: OFF, crypto: WinCNG, zlib: OFF }
          - { arch: x64  , plat: windows, logging: ON , shared: ON , crypto: WinCNG, zlib: OFF }
          - { arch: x64  , plat: windows, logging: OFF, shared: ON , crypto: WinCNG, zlib: OFF }
          - { arch: x64  , plat: uwp    , logging: OFF, shared: ON , crypto: WinCNG, zlib: OFF }
          - { arch: ARM64, plat: windows, logging: OFF, shared: ON , crypto: WinCNG, zlib: OFF }
          - { arch: ARM64, plat: uwp    , logging: OFF, shared: ON , crypto: WinCNG, zlib: OFF }
          - { arch: x86  , plat: windows, logging: OFF, shared: ON , crypto: WinCNG, zlib: OFF }
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1
      - name: Install dependencies
        shell: bash
        run: |
          vcpkg --triplet=${{ matrix.arch }}-${{matrix.plat}} install openssl zlib
      - name: Configure with CMake
        shell: bash
        run: |
          archgen=${{matrix.arch}}; [ "${archgen}" = 'x86' ] && archgen=Win32
          cmake . -B bin \
            -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DCMAKE_GENERATOR_PLATFORM=$archgen \
            -DVCPKG_TARGET_TRIPLET=${{matrix.arch}}-${{matrix.plat}} \
            -DENABLE_WERROR=ON \
            -DBUILD_SHARED_LIBS=${{matrix.shared}} \
            -DCRYPTO_BACKEND=${{matrix.crypto}} \
            -DENABLE_ZLIB_COMPRESSION=${{matrix.zlib}}
      - name: Build with CMake
        run: |
          cmake --build bin --config Release --target package
